require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - config/**/*.rb
    - spec/**/*.rb